### PR TITLE
Add go-beyond.org

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Someguy123** [comment]
@teran-mckinney Any evidence of this?

**Comment by ghost** [comment]
http://go-beyond.org/about/ and https://raw.githubusercontent.com/teran-mckinney/go-beyond.org/master/content/about.md

It's my site. In the source and the rendered HTML on go-beyond.org, you can see the potato... tor link.

I wonder if there's a standard form for tor domains in DNS. Maybe a TXT record.

**Comment by Someguy123** [comment]
Ah, I see it now.

Also there have been many discussions on a standardised HTTP header, DNS, etc. for this kind of thing, but nothing actually made a standard AFAIK.

Accepted.

**Comment by Someguy123** [comment]
Submitted to AMO as 0.1.8

**Comment by ghost** [comment]
Thank you! I appreciate it.

**Pull request merged**
