### PR TITLE
added Whonix.org

### PR DESCRIPTION
**Pull request by ghost**
added whonix.org

### CODE REVIEW

**Comment by Someguy123** [comment]
Where is this proven? I can't find it

**Comment by ghost** [comment]
Are you referring to the Sarah? She has it listed on her [Twitter](https://twitter.com/SarahJamieLewis) and [Keybase](https://keybase.io/sarahjamielewis)

**Comment by ghost** [comment]
Whonix.org's onion is on the footer of the site

**Comment by Someguy123** [comment]
@beardog108 Oh, I couldn't see that onion link on their site at first. Thanks for the clarification.

Merged 👍

**Pull request merged**
